## Importações das bibliotecas

In [1]:
import pandas as pd
import os
import kagglehub
import plotly.express as px

c:\Users\felip\OneDrive\git_work\Student-Course-Completion-Prediction-Dataset\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Lendo o dataset

In [9]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("nisargpatel344/student-course-completion-prediction-dataset")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.10), please consider upgrading to the latest version (0.4.1).
Path to dataset files: C:\Users\felip\.cache\kagglehub\datasets\nisargpatel344\student-course-completion-prediction-dataset\versions\1

In [10]:
def return_file(file_path):
   from pathlib import Path

   for file in Path(file_path).iterdir():
      if file.is_file():
         return file

In [11]:
os.makedirs("../data/preprocessed", exist_ok=True)

In [12]:
df = pd.read_csv(f"{str(path/return_file(path))}")
df

,Student_ID,Name,Gender,Age,Education_Level,Employment_Status,City,Device_Type,Internet_Connection_Quality,Course_ID,...,Enrollment_Date,Payment_Mode,Fee_Paid,Discount_Used,Payment_Amount,App_Usage_Percentage,Reminder_Emails_Clicked,Support_Tickets_Raised,Satisfaction_Rating,Completed
0,STU100000,Vihaan Patel,Male,19,Diploma,Student,Indore,Laptop,Medium,C102,...,01-06-2024,Scholarship,No,No,1740,49,3,4,3.5,Completed
1,STU100001,Arjun Nair,Female,17,Bachelor,Student,Delhi,Laptop,Low,C106,...,27-04-2025,Credit Card,Yes,No,6147,86,0,0,4.5,Not Completed
2,STU100002,Aditya Bhardwaj,Female,34,Master,Student,Chennai,Mobile,Medium,C101,...,20-01-2024,NetBanking,Yes,No,4280,85,1,0,5.0,Completed
3,STU100003,Krishna Singh,Female,29,Diploma,Employed,Surat,Mobile,High,C105,...,13-05-2025,UPI,Yes,No,3812,42,2,3,3.8,Completed
4,STU100004,Krishna Nair,Female,19,Master,Self-Employed,Lucknow,Laptop,Medium,C106,...,19-12-2024,Debit Card,Yes,Yes,5486,91,3,0,4.0,Completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,STU199995,Neha Singh,Female,34,Bachelor,Student,Hyderabad,Mobile,Medium,C104,...,12-07-2024,UPI,Yes,No,3285,100,3,2,3.8,Completed
99996,STU199996,Kavya Nair,Female,24,Bachelor,Self-Employed,Delhi,Mobile,High,C104,...,13-01-2024,UPI,Yes,No,3233,71,2,0,3.0,Not Completed
99997,STU199997,Neha Nair,Male,17,Master,Employed,Ahmedabad,Laptop,Medium,C107,...,14-08-2024,UPI,Yes,Yes,3820,61,2,0,4.1,Not Completed
99998,STU199998,Pooja Sharma,Female,28,Bachelor,Student,Ahmedabad,Mobile,High,C104,...,21-06-2025,Credit Card,Yes,No,3347,78,1,0,4.7,Not Completed
99999,STU199999,Rahul Patel,Male,29,Diploma,Student,Bengaluru,Laptop,Low,C105,...,15-03-2024,Credit Card,Yes,No,4120,55,1,0,3.9,Not Completed

In [13]:
lista_unicos = list(set(df['City'].to_list()))
lista_unicos

['Hyderabad',
 'Nagpur',
 'Delhi',
 'Chennai',
 'Kolkata',
 'Mumbai',
 'Bhopal',
 'Vadodara',
 'Jaipur',
 'Ahmedabad',
 'Surat',
 'Pune',
 'Lucknow',
 'Indore',
 'Bengaluru']

In [14]:
df.head()

,Student_ID,Name,Gender,Age,Education_Level,Employment_Status,City,Device_Type,Internet_Connection_Quality,Course_ID,...,Enrollment_Date,Payment_Mode,Fee_Paid,Discount_Used,Payment_Amount,App_Usage_Percentage,Reminder_Emails_Clicked,Support_Tickets_Raised,Satisfaction_Rating,Completed
0,STU100000,Vihaan Patel,Male,19,Diploma,Student,Indore,Laptop,Medium,C102,...,01-06-2024,Scholarship,No,No,1740,49,3,4,3.5,Completed
1,STU100001,Arjun Nair,Female,17,Bachelor,Student,Delhi,Laptop,Low,C106,...,27-04-2025,Credit Card,Yes,No,6147,86,0,0,4.5,Not Completed
2,STU100002,Aditya Bhardwaj,Female,34,Master,Student,Chennai,Mobile,Medium,C101,...,20-01-2024,NetBanking,Yes,No,4280,85,1,0,5.0,Completed
3,STU100003,Krishna Singh,Female,29,Diploma,Employed,Surat,Mobile,High,C105,...,13-05-2025,UPI,Yes,No,3812,42,2,3,3.8,Completed
4,STU100004,Krishna Nair,Female,19,Master,Self-Employed,Lucknow,Laptop,Medium,C106,...,19-12-2024,Debit Card,Yes,Yes,5486,91,3,0,4.0,Completed

In [15]:
df.isna().sum().sum()

np.int64(0)

In [16]:
pd.DataFrame(df.describe()).T

,count,mean,std,min,25%,50%,75%,max
Age,100000.0,25.709590,5.615292,17.0,21.0,25.0,30.0,52.0
Course_Duration_Days,100000.0,51.817300,20.324801,25.0,30.0,45.0,60.0,90.0
Instructor_Rating,100000.0,4.444478,0.202631,4.1,4.3,4.5,4.6,4.7
Login_Frequency,100000.0,4.785380,1.848289,0.0,3.0,5.0,6.0,15.0
Average_Session_Duration_Min,100000.0,33.878180,10.341964,5.0,27.0,34.0,41.0,81.0
Video_Completion_Rate,100000.0,62.174580,19.558126,5.0,48.5,64.0,77.5,99.9
Discussion_Participation,100000.0,2.329290,1.591365,0.0,1.0,2.0,3.0,12.0
Time_Spent_Hours,100000.0,3.873632,3.781185,0.5,0.5,2.7,6.2,25.6
Days_Since_Last_Login,100000.0,6.188860,6.982047,0.0,1.0,4.0,9.0,99.0
Notifications_Checked,100000.0,5.232110,2.401486,0.0,4.0,5.0,7.0,18.0
Peer_Interaction_Score,100000.0,6.294509,1.977552,0.0,4.9,6.3,7.7,10.0
Assignments_Submitted,100000.0,4.775430,1.664640,0.0,4.0,5.0,6.0,10.0
Assignments_Missed,100000.0,5.123450,1.692808,0.0,4.0,5.0,6.0,10.0
Quiz_Attempts,100000.0,3.772330,2.021276,0.0,2.0,4.0,5.0,16.0
Quiz_Score_Avg,100000.0,73.276201,12.552344,19.6,64.7,73.3,82.0,100.0
Project_Grade,100000.0,68.189534,15.312036,0.0,57.7,68.3,78.8,100.0
Progress_Percentage,100000.0,53.823104,12.495622,7.6,45.4,53.9,62.4,98.6
Rewatch_Count,100000.0,2.323930,1.580735,0.0,1.0,2.0,3.0,15.0
Payment_Amount,100000.0,3253.427120,2084.391775,0.0,1242.0,3715.0,4685.0,7149.0
App_Usage_Percentage,100000.0,67.859510,19.138354,0.0,55.0,68.0,82.0,100.0
Reminder_Emails_Clicked,100000.0,2.332650,1.584626,0.0,1.0,2.0,3.0,13.0
Support_Tickets_Raised,100000.0,0.870980,0.951569,0.0,0.0,1.0,1.0,8.0
Satisfaction_Rating,100000.0,4.132128,0.700895,1.0,3.7,4.2,4.7,5.0

In [17]:
age_count = df['Age'].value_counts().reset_index()
age_count.columns = ['Age', 'Count']
age_count

    Age  Count
0    17   9145
1    25   6649
2    26   6616
3    24   6460
4    27   6325
5    28   6168
6    23   6043
7    29   5650
8    22   5507
9    30   4973
10   21   4919
11   20   4427
12   31   4384
13   19   3731
14   32   3684
15   33   3123
16   18   3122
17   34   2410
18   35   1869
19   36   1393
20   37   1080
21   38    769
22   39    564
23   40    373
24   41    237
25   42    147
26   43     85
27   44     68
28   45     35
29   46     24
30   47     10
31   48      5
32   49      4
33   52      1

In [18]:
fig = px.bar(
   age_count,
   x = 'Age',
   y = 'Count',
   title='Distribuição por idade'
)
fig.show()

In [30]:
# Define os intervalos (bins)
bins = [0,20, 25, 30,35, 100]

# Define os rótulos das faixas
labels = [
   "até 20",
   "21-25",
   "26-30",
   "31-35",
   "36+",
]

# Cria a coluna com as faixas
df["Age_range"] = pd.cut(
    df["Age"],
    bins=bins,
    labels=labels,
    right=True,      # inclui o limite da direita
    include_lowest=True
)

# Conta por faixa
age_interval = df["Age_range"].value_counts().sort_index().reset_index()
age_interval.columns = ["Age_range", "Count"]

age_interval

  Age_range  Count
0    até 20  20425
1     21-25  29578
2     26-30  29732
3     31-35  15470
4       36+   4795

| Categoria             | Coluna                       | O que representa                    |
| --------------------- | ---------------------------- | ----------------------------------- |
| Identificação         | Student_ID                   | Identificador único do estudante    |
| Identificação         | Name                         | Nome do estudante                   |
| Perfil demográfico    | Gender                       | Gênero do estudante                 |
| Perfil demográfico    | Age                          | Idade do estudante                  |
| Perfil demográfico    | Education_Level              | Nível de escolaridade               |
| Perfil socioeconômico | Employment_Status            | Situação profissional               |
| Perfil socioeconômico | City                         | Cidade de residência                |
| Acesso e tecnologia   | Device_Type                  | Dispositivo principal de acesso     |
| Acesso e tecnologia   | Internet_Connection_Quality  | Qualidade da conexão com a internet |
| Acesso e tecnologia   | App_Usage_Percentage         | Percentual de uso via aplicativo    |
| Curso                 | Course_ID                    | Identificador do curso              |
| Curso                 | Course_Name                  | Nome do curso                       |
| Curso                 | Category                     | Área temática do curso              |
| Curso                 | Course_Level                 | Nível do curso                      |
| Curso                 | Course_Duration_Days         | Duração do curso em dias            |
| Instrutor             | Instructor_Rating            | Avaliação média do instrutor        |
| Engajamento           | Login_Frequency              | Frequência de acessos               |
| Engajamento           | Average_Session_Duration_Min | Duração média das sessões           |
| Engajamento           | Video_Completion_Rate        | Percentual de vídeos concluídos     |
| Engajamento           | Discussion_Participation     | Participação em fóruns              |
| Engajamento           | Time_Spent_Hours             | Total de horas dedicadas            |
| Engajamento           | Days_Since_Last_Login        | Dias desde o último acesso          |
| Engajamento           | Notifications_Checked        | Se verifica notificações            |
| Engajamento           | Peer_Interaction_Score       | Interação com outros alunos         |
| Engajamento           | Rewatch_Count                | Quantidade de revisualizações       |
| Avaliação acadêmica   | Assignments_Submitted        | Atividades entregues                |
| Avaliação acadêmica   | Assignments_Missed           | Atividades não entregues            |
| Avaliação acadêmica   | Quiz_Attempts                | Tentativas de quiz                  |
| Avaliação acadêmica   | Quiz_Score_Avg               | Média das notas dos quizzes         |
| Avaliação acadêmica   | Project_Grade                | Nota do projeto                     |
| Progresso             | Progress_Percentage          | Percentual de progresso no curso    |
| Temporal              | Enrollment_Date              | Data de matrícula                   |
| Financeiro            | Payment_Mode                 | Forma de pagamento                  |
| Financeiro            | Fee_Paid                     | Indica se houve pagamento           |
| Financeiro            | Discount_Used                | Uso de desconto                     |
| Financeiro            | Payment_Amount               | Valor pago                          |
| Comunicação e suporte | Reminder_Emails_Clicked      | Cliques em e-mails de lembrete      |
| Comunicação e suporte | Support_Tickets_Raised       | Chamados de suporte abertos         |
| Satisfação            | Satisfaction_Rating          | Avaliação geral do curso            |
| Variável alvo         | Completed                    | Indica se o curso foi concluído     |

## Preprocessamento

In [37]:
df_processed = df.copy()
df_processed.head()
#df_transformed.dtypes

,Student_ID,Name,Gender,Age,Education_Level,Employment_Status,City,Device_Type,Internet_Connection_Quality,Course_ID,...,Enrollment_Date,Payment_Mode,Fee_Paid,Discount_Used,Payment_Amount,App_Usage_Percentage,Reminder_Emails_Clicked,Support_Tickets_Raised,Satisfaction_Rating,Completed
0,STU100000,Vihaan Patel,Male,19,Diploma,Student,Indore,Laptop,Medium,C102,...,01-06-2024,Scholarship,No,No,1740,49,3,4,3.5,Completed
1,STU100001,Arjun Nair,Female,17,Bachelor,Student,Delhi,Laptop,Low,C106,...,27-04-2025,Credit Card,Yes,No,6147,86,0,0,4.5,Not Completed
2,STU100002,Aditya Bhardwaj,Female,34,Master,Student,Chennai,Mobile,Medium,C101,...,20-01-2024,NetBanking,Yes,No,4280,85,1,0,5.0,Completed
3,STU100003,Krishna Singh,Female,29,Diploma,Employed,Surat,Mobile,High,C105,...,13-05-2025,UPI,Yes,No,3812,42,2,3,3.8,Completed
4,STU100004,Krishna Nair,Female,19,Master,Self-Employed,Lucknow,Laptop,Medium,C106,...,19-12-2024,Debit Card,Yes,Yes,5486,91,3,0,4.0,Completed

In [38]:
lista_colunas_apagar = ['Student_ID', 'Name', 'Course_ID', 'Progress_Percentage','Satisfaction_Rating']
lista_unicos = set(lista_colunas_apagar)
print(f'{len(lista_unicos)} colunas unicas | {len(lista_colunas_apagar)} colunas totais')

5 colunas unicas | 5 colunas totais

In [39]:
df_processed = df_processed.drop(columns=lista_colunas_apagar)
df_processed.head()

,Gender,Age,Education_Level,Employment_Status,City,Device_Type,Internet_Connection_Quality,Course_Name,Category,Course_Level,...,Rewatch_Count,Enrollment_Date,Payment_Mode,Fee_Paid,Discount_Used,Payment_Amount,App_Usage_Percentage,Reminder_Emails_Clicked,Support_Tickets_Raised,Completed
0,Male,19,Diploma,Student,Indore,Laptop,Medium,Data Analysis with Python,Programming,Intermediate,...,0,01-06-2024,Scholarship,No,No,1740,49,3,4,Completed
1,Female,17,Bachelor,Student,Delhi,Laptop,Low,Machine Learning A-Z,Programming,Advanced,...,2,27-04-2025,Credit Card,Yes,No,6147,86,0,0,Not Completed
2,Female,34,Master,Student,Chennai,Mobile,Medium,Python Basics,Programming,Beginner,...,2,20-01-2024,NetBanking,Yes,No,4280,85,1,0,Completed
3,Female,29,Diploma,Employed,Surat,Mobile,High,UI/UX Design Fundamentals,Design,Beginner,...,4,13-05-2025,UPI,Yes,No,3812,42,2,3,Completed
4,Female,19,Master,Self-Employed,Lucknow,Laptop,Medium,Machine Learning A-Z,Programming,Advanced,...,4,19-12-2024,Debit Card,Yes,Yes,5486,91,3,0,Completed

In [ ]:
# Define os intervalos (bins)
bins = [0,20, 25, 30,35, 100]

# Define os rótulos das faixas
labels = [
   "até 20",
   "21-25",
   "26-30",
   "31-35",
   "36+",
]

# Cria a coluna com as faixas
df_processed["Age_range"] = pd.cut(
    df_processed["Age"],
    bins=bins,
    labels=labels,
    right=True,      # inclui o limite da direita
    include_lowest=True
)

df_processed

In [40]:
df_processed.to_csv('../data/preprocessed/student_completion_data.csv', index=False)